patternbot:
  source: "_patterns"
  destination: "pattern-library"
  font_url: false
  css:
    source: "css"
    modulifier: "modules.css"
    gridifier: "grid.css"
    typografier: "type.css"
    theme: "theme.css"
  icons:
    source: "images"
    filenames:
      - "icons"
    extensions:
      - ".svg"
  logos:
    source: "images"
    filenames:
      - "logo"
      - "logo-256"
      - "logo-64"
      - "logo-32"
      - "logo-16"
    extensions:
      - ".svg"
      - ".png"

  title: false
  title_backup: "Pattern Library"
  description: |
    This pattern library is the source for all the colours, fonts & styles available for our website.

  colors:
    background: '#fff'
    accent: false
    patterns:

  rationales:
