_layout: "patternbot_pattern_internal"
_extra_css:
  - 'icons/icons.min.css'

title: "Icons"
description: |
  The sprite sheet contains the following icons for use in the website. Combine the icons with [Modulifier](https://modulifier.web-dev.tools) & [Typografier](https://typografier.web-dev.tools) classes for lots of variability. [See the documentation for all available classes.](https://learn-the-web.algonquindesign.ca/topics/modulifier-cheat-sheet/)

patterns:
  icons:
    _popout_button: false
    _code: false
    _resizable: false
